### ISSUE TITLE
Old PBOs don't get cleaned

### ISSUE THREAD

**Issue by jonpas** [synixebrett/HEMTT#167] opened 2019-08-08 03:20 UTC
**HEMTT Version:** `0.6.2` (dev `09c0902cc3fce1305a99b4544ffaab122ed80e15`)
**Project:** https://github.com/Theseus-Aegis/TheseusServices/commit/cf1285abbea17bf7068622f6a9c401c31e3357c7

**Description:**

Old built PBOs of removed folders in `addons` (probably not from `optionals` either) folder do not get cleaned out. This happens with `build -f`, `clean` and `build --release -f`.

**Steps to reproduce:**

- Build mod
- Remove one of the folders
- Build mod
- Observe old PBO stays there

**Additional information:**

N/A

**HEMTT Output:**

It correctly shows what it does.

**Comment by synixebrett** [comment] 2019-08-13 12:10
Duplicate of #58, I will mark the other one as a bug

**Closed by synixebrett** 2019-08-13 12:10 UTC
Labels: bug
